### ISSUE TITLE
cannot find jniDir() in android studio

### ISSUE THREAD

**Issue by caifazhou** [eltorio/RtkGps#13]
When I try to use Android studio (2.2.3) to build this version of RtkGps, I got this error information:

Error:(46, 0) Could not find method jniDir() for arguments [/Users/***/***/RtkGps/libs] on task ':packageDebug' of type com.android.build.gradle.tasks.PackageApplication.
<a href="openFile:/Users/***/***/RtkGps/build.gradle">Open File</a>

I am totally new to jni, i cannot figure out what the problem is?Can you help me to solve it? Thanks
----
***: I replace my personal information with this.

**Comment by sunshine1995tangyao** [comment]
I have the same problem,and I try to use tasks.withType(com.android.build.gradle.tasks.PackageApplication) { pkgTask ->
    pkgTask.jniFolders = new HashSet<File>()
    pkgTask.jniFolders.add(new File(buildDir, 'libs'))
}
to replace it ,but still failed,
how do you solve it finally?

**Comment by eltorio** [comment]
Current build env compiles correctly
