### ISSUE TITLE
android rtklib 2.4.3 b29

### ISSUE THREAD

**Issue by elsol666** [eltorio/RtkGps#16]
Hi, great work eltorio,
but is there a chance to update the android stuff to b29 including the changes of tomojitakasu (https://github.com/tomojitakasu/RTKLIB/tree/rtklib_2.4.3)? He made some more bugfixes and the support of skytraq extended raw message is in your version also still missing! 

Would be great, thanks!

**Comment by rinex20** [comment]
Please refer the following:
https://github.com/rinex20/RtkGps/blob/master/demo5b29/apk

**Comment by rinex20** [comment]
new version released! @elsol666 
- fix mocklocation bug in Android M and later version.
- fine-tuning ar process option special for L1 low cost RTK,  DATAGNSS D302-RTK and skytraq module

**Comment by gto234** [comment]
@rinex20 
since you are building new versions of rtkgps can you please add the $GPGST NMEA output?
See [here](http://www.trimble.com/OEM_ReceiverHelp/V4.44/en/NMEA-0183messages_GST.html)
i will test your version later, for now i am using 2.4.2 p11

**Comment by rinex20** [comment]
@gto234 yes,I will add this sentense,please wait.

**Comment by gto234** [comment]
@rinex20 
thanks, can you also check the compatibility with android 4+?
On S3mini the app doesn't install at all and in android 4.4 in crashes on start.

**Comment by PatrickBernhart** [comment]
@rinex20
new RTKGNSS.apk not working with Android 7, crash after start. Can you fix this because i like use mock location

**Comment by rinex20** [comment]
@pb1966 please select rtk+ as mock location service provider in developer option before run rtk+

**Comment by caris2010** [comment]
RTKGNSS.apk not working with Android 6 also, crash after start. Already setting the mock in developer, but no luck. Anything miss?

**Comment by pb1966** [comment]
I try enable mock in dev setings, but the app crash with Android 7 :-(

**Comment by pb1966** [comment]
is it possible save the settings, because after a reinstall all settings have to do again? i do not found the installation directory and config file on my phone

**Comment by caris2010** [comment]
any good news about Mock Location feature?

**Comment by jdatalog** [comment]
Hi all,
@rinex20,any progress ?  It should be nice if you share your work. That will open the oportunity to help you.

**Comment by caris2010** [comment]
yes any progress please?? mock location

**Comment by sobido** [comment]
seems that Mapit (http://mapit-gis.com/) took the relay for RTKGSP+. call it Ntrip client.
doesn't work yet with Ublox format but OK with RTCM3 so far.
they also correct a bug in the minus sign possible when you give position of your BASE .

**Comment by sobido** [comment]
there is alos another RTKGPS+ version on geottaging+ [https://play.google.com/store/apps/details?id=com.geotaggingplusfree](url)

**Comment by caris2010** [comment]
Yes that is my own

**Comment by sobido** [comment]
@caris2010 
impressed & respect ! Geottaging+ works nice indeed. 
did you plan to propose also soon , for some Android smartphone , an input for Rover, with their own raw internal GNSS?

**Comment by caris2010** [comment]
Its depent on rtklib code...

**Comment by eltorio** [comment]
With help of gpsFan I upgraded to 2.4.23b29d

**Comment by jdatalog** [comment]
Thanks a lot  gpsFan and Ronan for your work.
Christophe

**Comment by caris2010** [comment]
I've just tried your new RTKGPS+.. its working well.. but not for MOCK Location.. Still crash exit program when the mock location activated..

**Comment by eltorio** [comment]
Dear Caris2010
You must enable the developer mode on your phone… Mock location is a developer option.

**Comment by caris2010** [comment]
Yes I did... But still no luck... May be the version of android???

**Comment by eltorio** [comment]
Perhaps, maybe you can launch it with Android studio 3.1 in debugger subsytem and send me back the error and the stack trace.
I currently develop on a Trimble SpectraPrecision MobileMapper 50 which is a very specific phone!
If you do not know how to launch… Download Android Studio it is so easy, after installing you can open clone directly from github
<img width="471" alt="capture d ecran 2018-08-05 a 10 43 43" src="https://user-images.githubusercontent.com/6966689/43684234-932d7b4a-989c-11e8-953d-6a1c9931ee94.png">
<img width="653" alt="capture d ecran 2018-08-05 a 10 44 00" src="https://user-images.githubusercontent.com/6966689/43684235-96ecc114-989c-11e8-84f3-4294daf6a513.png">

You may have multiple sdk and tools needed but Android Studio will ask you to download them automatically

**Comment by eltorio** [comment]
I can reproduce you problem
08-05 11:29:42.281 16630-16630/gpsplus.rtkgps E/RtkGps mock loc service: Mock Location is not allowed
08-05 11:29:52.440 16630-16683/gpsplus.rtkgps E/AndroidRuntime: FATAL EXCEPTION: IntentService[RtkNaviService]
    Process: gpsplus.rtkgps, PID: 16630
    java.lang.SecurityException: gpsplus.rtkgps from uid 10116 not allowed to perform MOCK_LOCATION

In developper setting do you add the good authorization?
On my development mobile (Android 6.0.)1 I did (in french):
![screenshot_20180805-113242](https://user-images.githubusercontent.com/6966689/43684742-0cd83710-98a6-11e8-85a1-0bbbb8f2bcd3.png)
![screenshot_20180805-113342](https://user-images.githubusercontent.com/6966689/43684745-1cad4e82-98a6-11e8-8c13-24caaf13195a.png)
![screenshot_20180805-113407](https://user-images.githubusercontent.com/6966689/43684746-1e55994c-98a6-11e8-83a8-d2c999fe5fc1.png)

**Comment by caris2010** [comment]
May be this cause the problem of mock location
Nothing  in select debug app. 
Should I refresh or re install the rtkgps+ ??

**Comment by eltorio** [comment]
You may try the version in 1.0_Alpha_26 branch which has a better permission handling

**Comment by caris2010** [comment]
sorry.. where can we find "version 1.0_Alpha_26"

**Comment by eltorio** [comment]
In GitHub you need to switch the current branch… Next the current app is in bin/.
All my app are signed with the same key so you can install them without loosing your settings.
Finally if you need an older version you might use the history in GitHub and browse the repository at a new commit stage.
<img width="735" alt="capture d ecran 2018-08-06 a 07 46 51" src="https://user-images.githubusercontent.com/6966689/43698996-06b59358-994d-11e8-9950-5332c9e50948.png">

**Comment by caris2010** [comment]
ok .. Thank you.. let me try first

**Comment by caris2010** [comment]
I just test your v26 , This show a completely wrong position. I do not know the problem, may be you forget a leap second (18) or something... Then I can not test the mock location feature
Its normal in your V25 but crash when mock location activated

**Comment by eltorio** [comment]
It is a 64 bits issue…
Same with x86_64 and arm64_v8a
I'll try to take some time to compile without 64bits, but compile it only for x86 and armeabi-v7a, remove x86_64 and arm64_v8a.

**Comment by eltorio** [comment]
Last 1.0_Alpha_26 is now built without 64bits support… please try

**Comment by caris2010** [comment]
Wow... Thx for your great response. Let me test and compare with mapit NTRIP

**Comment by caris2010** [comment]
roughly test.. looks normal.. great progress.. ( use ANDROID v7.1 auto upgrade from v6.xx)
1. Setting mock location -> rtkGPS+ , but Nothing in select debug app setting
2. check activate mock location in RTKGPS+ setting 
no crash issue
but the mock location output seem can not be used for others apps or not connected 
still show waiting for position in others apps when we use mock location

Am i missing something in setting ?

**Comment by caris2010** [comment]
Hi El.. good news... your last v26 is working normally in Android V.5xx  including the mock location feature
great improvement..

**Comment by eltorio** [comment]
Just, for knowing what is your target receiver and your target handled?

**Comment by caris2010** [comment]
I use ublox m8t. and old Sony Expedia z.. with android 5.xx. ..  the mock location still not working on Xiaomi with android 7.xx .

**Comment by ausioz** [comment]
It seems android removed mock location for api 23++.

https://developer.android.com/sdk/api_diff/23/changes/android.Manifest.permission.html

Im not sure is there any alternative or hard-coded way

**Comment by caris2010** [comment]
hi Eltorio... any others progress??
