### ISSUE TITLE
Using measurements from Android API

### ISSUE THREAD

**Issue by flytrex-vadim** [eltorio/RtkGps#18]
I'm looking into using this application with new Xiaomi Mi 8 that has dual frequency, multi-constellation GNSS chip built in.

At first glance it doesn't seem to support getting raw pseudorange measurements from the android (https://developer.android.com/guide/topics/sensors/gnss) 
Or am I missing some setting ?

**Comment by eltorio** [comment]
You’re right. I’ll wait for a better documentation from Google for writing a driver for the raw gnss api. There’s quite no app using this api today (except the google’s one written in matlab language)
