### ISSUE TITLE
Port to newer version of RTKLIB

### ISSUE THREAD

**Issue by SaBe** [eltorio/RtkGps#8]
Hello, I was wondering if someone is working on a port to a newer version of RTKLIB
so that we could support UBLOX M8T receivers with rawx protocol? Those work nicely on latest RTKLIB versions. I have been trying to build it but as I'm new to Android SDK not to mention the NDK, I have had some issues compiling it.

**Comment by applemuncy** [comment]
Greetings @SaBe  
Some time ago I was able to compile but not cleanly. My compiler failed on some of the other cpu platforms but at least it worked for mine, ARM7, if I remember correctly. 
Perhaps if you explain what issues you had with compiling?

**Comment by SaBe** [comment]
Thanks for the reply;

This is what I got out of it:

[armeabi armeabi-v7a mips x86] Compile        : proj <= rtodms.c
[armeabi armeabi-v7a mips x86] Compile        : proj <= vector1.c
[armeabi armeabi-v7a mips x86] SharedLibrary  : libproj.so
mipsel-linux-android-g++: error: unrecognized command line option '-mthumb'
make: *** [obj/local/mips/libproj.so] Error 1


So to me it looks like the Make file passes "-mthumb" to mips compiler while
it should be only passed to ARM compiler right?


I did a clean new install of the latest NDK to make sure it's fine as I wasn't
sure where this error is coming from!

Any ideas?

Br,
Sampo

**Comment by applemuncy** [comment]
Indeed, I vaguely remember reaching that roadblock. I think I got around it by either removing directories in lib or modifying build.gradle to only build what I needed.

**Comment by SaBe** [comment]
I managed to compile the native parts for ARM,  I feel really bad about my self, but I just told ndk-build to ignore all the errors... It seemed that everything but ARM platforms simply explode here.  I did not manage to build the rest of the app tough. ANT simply ses there is nothing to do and even the clean target seems to fail.. the fight continues..

**Comment by MRonz70** [comment]
Hi there,
I'm trying to recompile all with the 2.4.3b8 version of Rtklib.
No problem with the ndk but so now I have a new version for librtkgps.so, but, using Android Studio 1.5.0 on mac osx, I have big trouble with the appcompat library since I got a lot of errors regarding it.
Could you please also tell which IDE you used for this version compile?
Eclipse?
Android Studio old version?

Thank you!

**Comment by eltorio** [comment]
i use Eclipse on MacOS X,

**Comment by enocsanz** [comment]
Hi Ronan, 
nice to heard something from you! 
I want to encourage you to continue with the RTKGPS+ port for Android. 

Please!!! 

And thank you very much for the previous work.

**Comment by Scout-Dev** [comment]
Hello - I am able to build the RtkGps+ port for Android.  I would like to merge 2.4.3b8 version of Rtklib, any suggestions, recommendations?  I am using Eclipse Mars running on Ubuntu 14.04.  My goal is to use RtkGps+ with my UBLOX M8T, I am open to suggestions or an easier method to accomplish this, perhaps just merge changes necessary like RXM-RAWX and RXM-SFRBX messages.  I will be using NTRIP Corrections.

**Comment by gto234** [comment]
Hello all,
[here](https://www.optimalsystem.de/os/apps/rtkgps/RtkGps-Berca-2015-07-06.zip) you can find a working version of RTKGPS+ with patch 11.
It works great for me using novatel OEMV receivers.
I would like though more options on the mock location provider. E.g. to be able to send the location and other info like status fixed or float and accuracy to other apps.

**Comment by makeplan-rd** [comment]
Hi,
we are developing an interface system for your application, we need your source code to complete the project.

**Comment by eltorio** [comment]
All the source code is published on github

**Comment by makeplan-rd** [comment]
Hi @gto234, we tried to apply the patch 11 without success. The app can't recognize the bluetooth device anymore.
Is it possible to have the already patched source code? There's something wrong we can't figure out.

**Comment by gto234** [comment]
Sorry I don't have the source code.
I found the patched version on a [german](http://www.gpsforum.geospector.de/phpbb/viewtopic.php?f=4&t=3498&p=16790#p16792) forum so I don't know who build it.

**Comment by gto234** [comment]
If anyone willing to build a new version of RTGKPS+ please check this fix on the code posted [here](https://rtklibexplorer.wordpress.com/2016/02/26/improving-rtklib-solution-ar-lock-count-and-elevation-mask/) otherwise the fixed solution availability is not long because there is a bug in the code.
Thanks

**Comment by eltorio** [comment]
Upgraded to 2.4.3b29d
